### PR TITLE
Add pipeline-level nf-test

### LINKED ISSUE #93: Add pipeline-level nf-test
### Description of feature

Add pipeline-level nf-test

### PR DESCRIPTION
**Pull request by atrigila**
Closes #93 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] `CHANGELOG.md` is updated.

### CODE REVIEW

**Comment by atrigila** [comment]
A suffix that is added in `write_out_prepared_gex.R` is unstable. Even with the same input files, sometimes it appends that to the files and others it does not, creating a conflict with snapshots. I am going to modify that line to see if this solves the filename issue.

**Comment by atrigila** [comment]
The tests work well locally but produce files with different names in the CI and therefore fail.

**Comment by atrigila** [comment]
The issue is with multiqc outputs and versions in the CI. These differ from the local, most up-to-date multiqc. We switch back to an old multiqc version and re-test.

**Comment by atrigila** [comment]
Shoutout to @nschcolnicov for finding a solution to this issue🥇

**Review by apeltzer — APPROVED** [review]

**Pull request merged**
